// <auto-generated />
using System;
using ElectricityData.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ElectricityData.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20221119113616_Main")]
    partial class Main
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ElectricityData.Models.ElectricityModel", b =>
                {
                    b.Property<string>("OBJ_GV_TIPAS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OBJ_NUMERIS")
                        .HasColumnType("int");

                    b.Property<string>("OBT_PAVADINIMAS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PL_T")
                        .HasColumnType("datetime2");

                    b.Property<float?>("PMINUS")
                        .HasColumnType("real");

                    b.Property<float?>("PPlus")
                        .HasColumnType("real");

                    b.Property<string>("TINKLAS")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("ElectricityData");
                });

            modelBuilder.Entity("ElectricityData.Models.GroupedTinklasModel", b =>
                {
                    b.Property<float>("PMinusSum")
                        .HasColumnType("real");

                    b.Property<float>("PPlusSum")
                        .HasColumnType("real");

                    b.Property<string>("Tinklas")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("GroupedTinklas");
                });
#pragma warning restore 612, 618
        }
    }
}
